### set a color
 GET http://localhost:3000/auth/colors/green

### get the color
 GET http://localhost:3000/auth/colors





### update a user with a given id
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
    "email": "kushalpok01@gmail.com"
}


### delete a user with a given id
DELETE http://localhost:3000/auth/556



### Find all users with a given email
GET http://localhost:3000/auth?email=kushalpok0@gmail.com

### find a particular user with a given ID
GET http://localhost:3000/auth/9

### Who am I; Get the currently signed in user
GET http://localhost:3000/auth/whoami

### logout the signed in user
POST http://localhost:3000/auth/signout


### create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
"email": "latesst@gmail.com",
"password": "latestpw"
}

### signin a user as an existing user
POST http://localhost:3000/auth/signin 
Content-Type: application/json

{
    "email": "latest@gmail.com",
    "password": "latestpw"
}






